baseURL = "https://anno4862.github.io/"
languageCode = "en-us"
title = "benhattem.nl"
theme = "hugo-m10c-benh"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[params]
  author = "Ben Hattem"
  description = "Ben's personal websit."
  menu_item_separator = " - "
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/anno4862"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/benhattem/"
